
% ======================================================================= %
%                                                                         %
% This script plots the monthly and annual distribution of the data used  %
% to force SLAMS. The data array has been generated by previously running %
% the script createSlamsInputData.m.                                      %
%                                                                         %
%   Version 1.0 - Completed 10 Jan 2026                                 %
%                                                                         %
% ======================================================================= %

close all; clear all; clc
addpath(genpath(fullfile('.','modelresources','external')))
addpath(fullfile('.','modelresources','internal')) 
addpath(fullfile('.','data','processed')) 
addpath(fullfile('.','code','matlab')) 
addpath('figures');

% =========================================================================
%%
% -------------------------------------------------------------------------
% SECTION 1 - PRESETS (CHANGE ACCORDINGLY)
% -------------------------------------------------------------------------

% Name of experiment (change accordingly)
testrunDir = 'GLOBALSTD';
figureSubfolder = 'GLOBALSTD';

% Choices to be applied (change accordingly)
choiceTypeGridDomain = 1; % 1=global, 2=local, 3=global with zoom in factor
choicePar0level = 0;      % 1=zeu calculated as 1% PAR0, 0=zeu calculated as 0.1% PAR0
choiceTargetDepth = 100;   % m (target depth for mapping in this script)

% =========================================================================
%%
% -------------------------------------------------------------------------
% SECTION 2 - PRESETS (DO NOT CHANGE)
% -------------------------------------------------------------------------

% Directories
filenameInputForcing        = 'slamsForcing.mat';
filenameInputRunGrid        = 'grid_run.mat';
filenameInputNumDepthLayers = 'waterColNumDepthLayers.txt';
filenameOutputGeoForcing    = 'slamsForcingGeo.mat';

% Path declarations
fullpathTestDir             = fullfile('.','tests',testrunDir);
fullpathModelInputDataDir   = fullfile(fullpathTestDir,'modelinputdata');

% Load configuration parameters used in the model
config = loadModelConfigurationParameters(fullpathModelInputDataDir,...
    filenameInputRunGrid,filenameInputNumDepthLayers,choiceTypeGridDomain);

% =========================================================================
%%
% -------------------------------------------------------------------------
% SECTION 3 - LOAD INPUT DATA ARRAY
% -------------------------------------------------------------------------

% Generated by createSlamsInputData.m
load(fullfile(fullpathModelInputDataDir,filenameInputForcing),'mapStruct'); 

% =========================================================================
%%
% -------------------------------------------------------------------------
% SECTION 4 - CALCULATE PFT DATA AND LIGHT PROPERTIES USING THE SUBROUTINE 
% THAT SEEDS PHYTOPLANKTON FUNCTIONAL TYPES IN SLAMS
% -------------------------------------------------------------------------

[monthlyProbPft,monthlyMuPft,monthlyPar0,monthlyZeu] = calculatePftData(...
    mapStruct,choicePar0level,config);

% =========================================================================
%%
% -------------------------------------------------------------------------
% SECTION 5 - ORGANISE ALL INPUT DATA FOR MAPPING
% -------------------------------------------------------------------------

% Organise input data into a structure
monthlyData = struct( ...
    'Mesozoo', mapStruct.monthlyMesozoo, ...
    'Nit', mapStruct.monthlyNit, ...
    'Sil', mapStruct.monthlySil, ...
    'Phos', mapStruct.monthlyPhos, ...
    'Oxy', mapStruct.monthlyOxy, ...
    'Temp', mapStruct.monthlyTemp, ...
    'Rho', mapStruct.monthlyRho, ...
    'Omegac', mapStruct.monthlyOmegaC, ...
    'Chla', mapStruct.monthlyChla, ...
    'Dust', mapStruct.monthlyDust, ...
    'Mld', mapStruct.monthlyMld, ...
    'Npp', mapStruct.monthlyNpp, ...
    'Par0', monthlyPar0, ...
    'Zeu', monthlyZeu, ...
    'DynVisco', mapStruct.monthlyDynVisco, ...
    'ProbPft', monthlyProbPft,...
    'MuPft', monthlyMuPft);

% =========================================================================
%%
% -------------------------------------------------------------------------
% SECTION 6 - CALCULATE ANNUAL AVERAGES
% -------------------------------------------------------------------------

annualData = struct();
fields = fieldnames(monthlyData);
for iField = 1:length(fields)
    fieldName = fields{iField};
    annualData.(fieldName) = calculateAnnualAverage(monthlyData.(fieldName));
end

waterRho = annualData.Rho(1:20,:);
waterDynVisco = annualData.DynVisco(1:20,:);
meanWaterRho = nanmean(waterRho(:));
meanDynVisco = nanmean(waterDynVisco(:));

% =========================================================================
%%
% -------------------------------------------------------------------------
% SECTION 7 - REPOSITION DATA FROM LOCATION SEQUENCE TO LAT X LON ARRAY
% -------------------------------------------------------------------------

forcingDataGeo = struct();

% Determine the dimensions of geoData fields based on the type of data 
% (depth-dependent, PFT, or surface ocean)
for iField = 1:length(fields)
    fieldName = fields{iField};
    [annualSize,monthlySize] = getArrayDataSize(annualData.(fieldName),config.nLats,config.nLons);
    forcingDataGeo.(['annual' fieldName]) = NaN(annualSize);
    forcingDataGeo.(['monthly' fieldName]) = NaN(monthlySize);
end

% Loop over locations and populate geoData
for iLoc = 1:config.nLocs
    iLat = config.iyBb(iLoc);
    iLon = config.ixBb(iLoc);
    
    for iField = 1:length(fields)
        fieldName = fields{iField};

        if size(annualData.(fieldName),1) > 12 % depth-dependent data
            forcingDataGeo.(['annual' fieldName])(iLat,iLon,:) = annualData.(fieldName)(:,iLoc);
            forcingDataGeo.(['monthly' fieldName])(iLat,iLon,:,:) = monthlyData.(fieldName)(:,:,iLoc);
        elseif size(annualData.(fieldName),1) == 4 % PFT data
            forcingDataGeo.(['annual' fieldName])(iLat,iLon,:) = annualData.(fieldName)(:,iLoc);
            forcingDataGeo.(['monthly' fieldName])(iLat,iLon,:,:) = monthlyData.(fieldName)(:,:,iLoc);   
        else % surface ocean data
            forcingDataGeo.(['annual' fieldName])(iLat,iLon) = annualData.(fieldName)(iLoc);
            forcingDataGeo.(['monthly' fieldName])(iLat,iLon,:) = monthlyData.(fieldName)(:,iLoc);    
        end

    end
end

% Save for use in other functions
save(fullfile(fullpathModelInputDataDir,filenameOutputGeoForcing),'forcingDataGeo','-v7.3')

% =========================================================================
%%
% -------------------------------------------------------------------------
% SECTION 8 - PLOT GLOBAL MAPS WITH PFT PROPERTIES AND ENVIRONMENTAL FORCING 
% FOR SLAMS 
% -------------------------------------------------------------------------

% Datasets metadata (in this order to plot)
datasetsMetadata = { % all data already comes lat x lon
    'Npp',      sprintf('Depth-integrated NPP,\n ESA-BICEP'),                     'mg C m^{-2} d^{-1}',    'algae',    0,    900, false, true,  3600*24*config.molarMassCarbon*1e3; % mol C m-2 s-1 --> mg C m-2 d-1 
    'Mesozoo',  sprintf('Mesozooplankton biomass in the upper 200 m,\n CMIP6-PISCES'),               'mg C m^{-2}',           'matter',   0,    900, false, false, NaN; 
    'Dust',     sprintf('Aeolian dust deposition flux,\n CMIP6-NCAR/CESM2'),                         'mg clay m^{-2} d^{-1}', 'turbid',0.01,    100, false, true,  3600*24*1e3; % g clay m-2 s-1 --> mg clay m-2 d-1              
    'Chla',     sprintf('Depth-integrated Chla concentration,\n ESA-OCCCI'),                'mg m^{-3}',             'algae',    0,      1, false, false, NaN; 
    'Par0',     sprintf('Surface PAR,\n NASA-MODIS'),                 'W m^{-2}',              'solar',    20,    130, false, false, NaN;
    'Mld',      sprintf('MLD,\n IFREMER/LOPS'),                                        'm',                     'deep',     20,    170, false, false, NaN; 
    'Temp',     sprintf('Temperature at %d m\n WOA23',choiceTargetDepth),                            'ºC',                    'thermal', 0,     28, true,  false, NaN; 
    'Rho',      sprintf('Density at %d m,\n calculated from WOA23',choiceTargetDepth),               'g cm^{-3}',             'dense', 1.022, 1.028, true,  false, NaN;
    'DynVisco', sprintf('Dynamic viscosity at %d m,\n calculated from WOA23',choiceTargetDepth),     'g cm^{-1} s^{-1}',      'ice',   0.009, 0.017, true,  false, NaN; 
    'Nit',      sprintf('Nitrate concentration at %d m,\n WOA23',choiceTargetDepth),                 'mmol m^{-3}',           'haline',   0,     30, true,  false, NaN;        
    'Sil',      sprintf('Silicate concentration at %d m,\n WOA23',choiceTargetDepth),                'mmol m^{-3}',           'haline',   0,     50, true,  false, NaN;  
    'Phos',     sprintf('Phosphate concentration at %d m,\n WOA23',choiceTargetDepth),               'mmol m^{-3}',           'haline',   0,    2.2, true,  false, NaN;  
    'Oxy',      sprintf('Oxygen concentration at %d m,\n WOA23',choiceTargetDepth),                  'mL L^{-1}',             'oxy',      2,      7, true,  false, NaN;                        
    'Omegac',   sprintf('Calcite saturation state at %d m,\n GLODAPv2/CO2SYS',choiceTargetDepth),    '',                      'dense',    2,      6, true,  false, NaN;  
};

% Plotting functions
plotEnvironmentalForcing(figureSubfolder,strcat(testrunDir,'_forcing'),...
    forcingDataGeo,datasetsMetadata,choiceTargetDepth,config)
% plotRelativePercentagePfts(figureSubfolder,strcat(testrunDir,'_pft_relat'),...
%     forcingDataGeo.annualProbPft,forcingDataGeo.monthlyProbPft,config)
% plotGrowthRatePfts(figureSubfolder,strcat(testrunDir,'_pft_growthrate'),forcingDataGeo.annualMuPft,forcingDataGeo.monthlyMuPft,config)

% =========================================================================
%%
% -------------------------------------------------------------------------
% LOCAL FUNCTIONS
% -------------------------------------------------------------------------

function [monthlyProbPft,monthlyMuPft,monthlyPar0,monthlyZeu] =...
    calculatePftData(mapStruct,choicePar0level,config)

    % This function is as PhytoSeedingProbabilities in primaryproduction.F90

    % Precompute avgPar0 for each location
    % Calculate daily mean PAR0 for an average day in a month
    monthlyPar0 = NaN(12,config.nLocs);
    for iLoc = 1:config.nLocs
        addPar0 = zeros(12,1);
        iMonth = 1;

        for iDay = 1:365
            dailyPar0daylight = mapStruct.dailyPar0daylight(iDay, iLoc);
            if isnan(dailyPar0daylight)
                dailyPar0daylight = 0; % replace NaN with 0 so that it can be summed
            end
            addPar0(iMonth) = addPar0(iMonth) + dailyPar0daylight;      
            if (mod(iDay,config.julianDayInMonth(iMonth)) == 0)
                iMonth = iMonth + 1;
            end         
        end

        monthlyPar0(:,iLoc) = addPar0 ./ config.nDaysPerMonth';
    end

    % Initialise output arrays
    monthlyProbPft = NaN(4,12,config.nLocs); % frac
    monthlyMuPft   = NaN(4,12,config.nLocs); % d-1
    monthlyZeu     = NaN(12,config.nLocs); % m

    for iLoc = 1:config.nLocs

        % Calculate depth layers
        nValidDepthLayers = sum(~isnan(config.gridDepths(:,iLoc))); % count valid depth layers
        localDepths = config.gridDepths(1:nValidDepthLayers,iLoc); % extract valid depths

        forcProbPft = NaN(4,12);
        forcMuPft   = NaN(4,12);
        
        for iMonth = 1:12

            % Skip processing for months with no light, no chla or no MLD
            if monthlyPar0(iMonth,iLoc) <= 0 ||...
                isnan(mapStruct.monthlyChla(iMonth,iLoc)) || ...
                isnan(mapStruct.monthlyMld(iMonth,iLoc))
                continue;
            end

            % Calculate zeu (depth where PARz > 1% of PAR0)
            [zeu,kpar] = calculateZeuFromChlaAndMLD(mapStruct.monthlyChla(iMonth,iLoc),...
                mapStruct.monthlyMld(iMonth,iLoc),choicePar0level);
                
            % The above is equivalent to this other way I was using before
            parz = monthlyPar0(iMonth,iLoc).*exp(-kpar.*localDepths(:)); % W m-2 
            validDepthIdx = (parz ./ monthlyPar0(iMonth,iLoc)) >= 1e-3;
            nLocalDepthsToSeedPhyto = sum(validDepthIdx);

            if nLocalDepthsToSeedPhyto == 0
                monthlyZeu(iMonth,iLoc) = 0;
                continue;
            end

            % Process phytoplankton growth at valid depths
            validNit = mapStruct.monthlyNit(validDepthIdx,iMonth,iLoc);
            validNpp = mapStruct.monthlyNpp(iMonth,iLoc);

            if any(validNit > 0) && validNpp > 0
                [muLimFactorPft(:,validDepthIdx), muNetPft(:,validDepthIdx), chlToCarbonPft(:,validDepthIdx)] = ...
                    calculatePhytoGrowthRate(...
                        mapStruct.monthlyNit(validDepthIdx,iMonth,iLoc), ...
                        mapStruct.monthlySil(validDepthIdx,iMonth,iLoc), ...
                        mapStruct.monthlyPhos(validDepthIdx,iMonth,iLoc), ...
                        mapStruct.monthlyTemp(validDepthIdx,iMonth,iLoc), ...
                        parz(validDepthIdx), config.pft.q10, config.pft.tempRef, ...
                        config.pft.muMax0degPft, config.pft.kNO3Pft, ...
                        config.pft.kPO4Pft, config.pft.kSiDiat, config.pft.chlToCarbonMax, ...
                        config.pft.alphaChlSpecificPft, config.pft.muThreshold);
            else
                muLimFactorPft = NaN(4,nLocalDepthsToSeedPhyto);
                muNetPft = NaN(4,nLocalDepthsToSeedPhyto);
                chlToCarbonPft = NaN(4,nLocalDepthsToSeedPhyto);
            end

            % Store zeu value for the month and location
            monthlyZeu(iMonth,iLoc) = localDepths(nLocalDepthsToSeedPhyto);

            % Calculate probabilities of seeding for each PFT and depth
            muNetPftSum = sum(muNetPft,2,'omitnan'); % sum over depth layers for each PFT
            muNetTotal = sum(muNetPftSum,'omitnan');

            if muNetTotal > 0
                probPft = muNetPftSum ./ muNetTotal;
                probPftAtDepth = muNetPft ./ muNetPftSum;

                % Assign probabilities and growth rates
                forcProbPft(:,iMonth) = probPft;
                forcMuPft(:,iMonth) = mean(muNetPft(:,1:nLocalDepthsToSeedPhyto),2,'omitnan'); % d-1
            end

        end % iMonth

        % Store output for current location
        monthlyProbPft(:,:,iLoc) = forcProbPft;
        monthlyMuPft(:,:,iLoc) = forcMuPft;

    end % iLoc

    % NOTE: Cphyto cannot be calculated as NPP_phyto/mu_phyto (from 
    % NPP_phyto = mu_phyto x Cphyto). But we can calculate NPP_phyto 
    % (mg C m-2 d-1) and the relative abundance of each PFT will be the 
    % same as that shown by monthlyProbPft calculated from mu.

    % % Calculate Cphyto
    % 
    % addCarbon = zeros(4,12,config.nLocs);
    % for iLoc = 1:config.nLocs   
    %     for iMonth = 1:12
    %         amountCarbonPerSeedingEvent = nppMonthly(iMonth,iLoc).*(config.molarMassCarbon*1000*config.depthLayerArea*3600*24)/20; % mol C m-2 s-1 --> mg C 
    %         if (sum(probPftMonthly(:,iMonth,iLoc)) > 0)
    %             for iSeedingEvent = 1:20
    %                 iPft = randsample(1:4, 1, true, squeeze(monthlyProbPft(:,iMonth,iLoc)));
    %                 addCarbon(iPft,iMonth,iLoc) = addCarbon(iPft,iMonth,iLoc) + amountCarbonPerSeedingEvent; % mg C
    %             end
    %         end
    %     end
    % end
    % 
    % monthlyNppPhyto = addCarbon./(config.depthLayerArea*3600*24); % mg C --> mg C m-2 s-1
    % 
    % monthlyCphyto = zeros(4,12,config.nLocs);
    % for iLoc = 1:config.nLocs
    %     for iMonth = 1:12
    %         for iPft = 1:4
    %             pftGrowthRate = monthlyMuPft(iPft,iMonth,iLoc)./(3600*24); % s-1
    %             monthlyCphyto(iPft,iMonth,iLoc) = monthlyNppPhyto(iPft,iMonth,iLoc)/(monthlyZeu(iMonth,iLoc)*pftGrowthRate); % mg C m-3
    %         end
    %     end
    % end
    % monthlyCphyto(isnan(monthlyCphyto)) = 0;

end % calculatePftData

% *************************************************************************

function annualField = calculateAnnualAverage(fieldData)
   
    if size(fieldData, 1) > 12
        % Depth-dependent data
        annualField = squeeze(mean(fieldData, 2, 'omitnan'));
    elseif size(fieldData, 1) == 4
        % PFT data
        annualField = squeeze(mean(fieldData, 2, 'omitnan'));
    else
        % Surface ocean data
        annualField = squeeze(mean(fieldData, 1, 'omitnan'));
    end
    
end % calculateAnnualAverage

% *************************************************************************

function [annualSize,monthlySize] = getArrayDataSize(fieldData,nLats,nLons)

    if size(fieldData, 1) > 12
        % Depth-dependent data
        annualSize = [nLats, nLons, size(fieldData,1)];
        monthlySize = [nLats, nLons, size(fieldData,1), 12];
    elseif size(fieldData, 1) == 4
        % PFT data
        annualSize = [nLats, nLons, 4];
        monthlySize = [nLats, nLons, 4, 12];
    else
        % Surface ocean data
        annualSize = [nLats, nLons];
        monthlySize = [nLats, nLons, 12];
    end
    
end % getArrayDataSize
     
% *************************************************************************        

function plotEnvironmentalForcing(figureSubfolderName,figurePrefixName,...
    forcingDataGeo,datasetsMetadata,choiceTargetDepth,config)


    [~,idxTargetDepth] = min(abs(config.gridDepths(:,1) - choiceTargetDepth));

    annualMeanData = NaN(config.nLats,config.nLons,length(datasetsMetadata));
    monthlyMeanData = NaN(config.nLats,config.nLons,12,length(datasetsMetadata));
    
    cbString = cell(length(datasetsMetadata),1); 
    cbPalette = cell(length(datasetsMetadata),1);
    caxisMin = zeros(length(datasetsMetadata),1);
    caxisMax = zeros(length(datasetsMetadata),1);
    
    for iTimescale = 1:2
        switch iTimescale
            case 1
                timeScale = 'monthly';
            case 2
                timeScale = 'annual';
        end
        for iDataset = 1:height(datasetsMetadata)
            baseFieldName = datasetsMetadata{iDataset,1};
            hasDepth = datasetsMetadata{iDataset,7};
            needsConversion = datasetsMetadata{iDataset,8};
            unitsFactor = datasetsMetadata{iDataset,9};

            % Construct dynamic field name
            fieldName = [timeScale baseFieldName];
            if isfield(forcingDataGeo, fieldName)
                varValue = forcingDataGeo.(fieldName);
            end

            % Integrate Mesozoo if required
            if contains(baseFieldName,'Mesozoo')
                % Zooplankton: integrate over depth using trapezoidal integration
                 varValue = integrateOverDepth(varValue,config); % mg C m-3 --> mg C m-2
            end
            % Apply unit conversion if needed
            if needsConversion
                varValue = varValue.*unitsFactor;
            end
            % Extract the slice at target depth if applicable
            if hasDepth
                if ndims(varValue) == 3
                    % Annual: lat x lon x depth
                    varValue = squeeze(varValue(:,:,idxTargetDepth));
                elseif ndims(varValue) == 4
                    % Monthly: lat x lon x depth x time (months)
                    varValue = squeeze(varValue(:,:,idxTargetDepth,:));
                end
            end

            % Check if the data spans multiple orders of magnitude (log10 values) and 
            % decide whether to apply a log10 transformation.
            caxisMin(iDataset) = cell2mat(datasetsMetadata(iDataset,5));
            caxisMax(iDataset) = cell2mat(datasetsMetadata(iDataset,6));
            cbPalette{iDataset} = cmocean(datasetsMetadata{iDataset,4});
            cbString{iDataset} = datasetsMetadata{iDataset,3};  
            orderMin = log10(caxisMin(iDataset));
            if caxisMin(iDataset) == 0
                orderMin = 0;
            end
            orderMax = log10(caxisMax(iDataset));
            if (max(orderMax,orderMin) - min(orderMax,orderMin)) >= 3 % if the difference in orders of magnitude >= 4
                varValue = log10(varValue);
                caxisMin(iDataset) = log10(caxisMin(iDataset));
                caxisMax(iDataset) = log10(caxisMax(iDataset));
                cbString{iDataset} = [cbString{iDataset}, ' (log10)'];
            end
              
            switch iTimescale
                case 1
                    monthlyMeanData(:,:,:,iDataset) = varValue;
                case 2
                    annualMeanData(:,:,iDataset) = varValue;
            end
        end % iDataset
    end % iTimescale

    % Plot the annual mean data using the custom plotting function
    isCommonColourBar = false;
    % for iDataset = 1:height(datasetsMetadata)
    %     datasetName = lower(datasetsMetadata{iDataset,1});
    %     sgTitle = datasetsMetadata(iDataset,2);
    %     titleStr = config.mappingProps.labelMonths;
    %     plotOceanVariableMaps(monthlyMeanData(:,:,:,iDataset),...
    %         config.mappingProps.mapLons,config.mappingProps.mapLats,...
    %         cbPalette{iDataset},cbString{iDataset},caxisMin(iDataset),...
    %         caxisMax(iDataset),isCommonColourBar,titleStr,...
    %         strcat(figurePrefixName,'_monthly_',datasetName),figureSubfolderName,sgTitle)
    % end

    titleStr = datasetsMetadata(:,2);
    plotOceanVariableMaps(annualMeanData,config.mappingProps.mapLons,...
        config.mappingProps.mapLats,cbPalette,cbString,caxisMin,caxisMax,isCommonColourBar,...
        titleStr,strcat(figurePrefixName,'_annual'),figureSubfolderName,[])

end % plotEnvironmentalForcing

% *************************************************************************

function plotRelativePercentagePfts(figureSubfolderName,figurePrefixName,...
    annualProbPft,monthlyProbPft,config)

% annualProbPft = forcingDataGeo.annualProbPft;
% monthlyProbPft = forcingDataGeo.monthlyProbPft;

    annualProbPftPreferredOrder = annualProbPft(:, :, [1, 3, 2, 4]); % swap coccos and flagel
    monthlyProbPftPreferredOrder = monthlyProbPft(:, :, [1, 3, 2, 4], :); % swap coccos and flagel

    cbString = 'Relative biomass dominance (%)';
    caxisMin = 0;
    caxisMax = 60;
    isCommonColourBar = 1;
    cbPalette = config.mappingProps.myColourMapOceanVars; %cmocean('delta');

    for iFigure = 1:3

        if (iFigure == 1)

            oceanVar = 100.*annualProbPftPreferredOrder;
            plotOceanVariableMaps(oceanVar,config.mappingProps.mapLons,...
                config.mappingProps.mapLats,cbPalette,cbString,caxisMin,...
                caxisMax,isCommonColourBar,config.mappingProps.labelFourPfts,...
                strcat(figurePrefixName,'_four'),figureSubfolderName,[])

        % elseif (iFigure == 2)
        % 
        %     [nRow,nCol,~] = size(annualProbPft);
        %     oceanVar = zeros(nRow,nCol,3);
        %     oceanVar(:,:,1) = 100.*(annualProbPftPreferredOrder(:,:,1)+annualProbPftPreferredOrder(:,:,3));
        %     oceanVar(:,:,2) = 100.*annualProbPftPreferredOrder(:,:,2);
        %     oceanVar(:,:,3) = 100.*annualProbPftPreferredOrder(:,:,4);
        % 
        %     plotOceanVariableMaps(oceanVar,config.mappingProps.mapLons,...
        %         config.mappingProps.mapLats,cbPalette,cbString,caxisMin,...
        %         caxisMax,isCommonColourBar,config.mappingProps.labelThreePfts,...
        %         strcat(figurePrefixName,'_three'),figureSubfolderName,[])
        % 
        % elseif (iFigure == 3)
        % 
        %     for iPft = 1:4
        %         oceanVar = 100.*squeeze(monthlyProbPftPreferredOrder(:,:,iPft,:));
        %         plotOceanVariableMaps(oceanVar,config.mappingProps.mapLons,...
        %             config.mappingProps.mapLats,cbPalette,cbString,caxisMin,...
        %             caxisMax,isCommonColourBar,config.mappingProps.labelMonths,...
        %             strcat(figurePrefixName,'_four_bymonth_',num2str(iPft)),...
        %             figureSubfolderName,config.mappingProps.labelFourPfts(iPft))
        %     end
        % 
        end

    end % iFigure

end % plotRelativePercentagePfts

% *************************************************************************

function plotGrowthRatePfts(figureSubfolderName,figurePrefixName,annualMuPft,...
    monthlyMuPft,config)

    cbString = 'Growth rate (d^{-1})';
    caxisMin = 0;
    caxisMax = 0.7;
    isCommonColourBar = 1;

    for iFigure = 1:3

        if (iFigure == 1)

            oceanVar = annualMuPft;
            plotOceanVariableMaps(oceanVar,config.mappingProps.mapLons,config.mappingProps.mapLats,...
                config.mappingProps.myColourMapOceanVars,cbString,caxisMin,caxisMax,...
                isCommonColourBar,config.mappingProps.labelFourPfts,figurePrefixName,...
                figureSubfolderName,[])

        elseif (iFigure == 2)

            for iPft = 1:4
                oceanVar = squeeze(monthlyMuPft(:,:,iPft,:));
                plotOceanVariableMaps(oceanVar,config.mappingProps.mapLons,...
                    config.mappingProps.mapLats,config.mappingProps.myColourMapOceanVars,...
                    cbString,caxisMin,caxisMax,isCommonColourBar,config.mappingProps.labelMonths,...
                    strcat(figurePrefixName,'_bymonth_',num2str(iPft)),...
                    figureSubfolderName,config.mappingProps.labelFourPfts(iPft))
            end
        end

    end % iFigure

end % plotGrowthRatePfts

% *************************************************************************