
% ======================================================================= %
%                                                                         %
% This script plots SLAMS' biogeochemical flux outputs and particle       % 
% numbers from test cases.                                                %              
%                                                                         %
% The script has 3 sections:                                              %
%   Section 1 - Presets.                                                  %
%   Section 2 - Load selected model input and output.                     %
%   Section 3 - Plot modelled flux data by station and month.             %
%   Section 4 - Plot modelled particle number data by station and month.  %
%                                                                         %
%   WRITTEN BY A. RUFAS, UNIVERISTY OF OXFORD                             %
%   Anna.RufasBlanco@earth.ox.ac.uk                                       %
%                                                                         %
%   Version 1.0 - Completed 21 May 2025                                   %
%                                                                         %
% ======================================================================= %

close all; clear all; clc
addpath(genpath('./data/raw/'));
addpath(genpath('./data/processed/'));
addpath(genpath('./code/matlab/'));
addpath(genpath('./modelresources/external/'));
addpath(genpath('./modelresources/internal/'));

% =========================================================================
%%
% -------------------------------------------------------------------------
% SECTION 1 - PRESETS
% -------------------------------------------------------------------------

% Name of test cases
testrunDir = {'LOCALTS6'; 'LOCALTS68yr'; 'LOCALTS612yr'};
testLegend = {'6 yr','8 yr','12 yr'};
% testrunDir = {'LOCALTS6'; 'LOCALTS68yr'};
% testLegend = {'Standard (Stokes)','vsink from Cael et al. (2018)'};
% testrunDir = {'LOCALTS6'; 'LOCALTS6rep'; 'LOCALTS6rand'; 'LOCALTS6long'; 'LOCALTS6extralong'};
% testLegend = {'Standard (8yrs, repeat seq)','Copy standard','Non-repeatable seq','16 years','30 years'};

% Folder output
figuresSubfolderName = 'test_end_time';

% Select
choiceTypeGridDomain = 2; % 1=global, 2=local, 3=global with zoom in factor

% Filename declarations
filenameInputSlamsOutput    = 'runsoutput.mat';
filenameInputRunGrid        = 'grid_run.mat';
filenameInputNumDepthLayers = 'waterColNumDepthLayers.txt';
filenameInputForcing        = 'slamsForcing.mat';

% Order of locations in modelled output
locationOrderInModel = {'EqPac','HOT/ALOHA','BATS/OFP','PAP-SO','OSP','HAUSGARTEN'}; % as in config.gridLats, config.gridLons
locationTags = {'eqpac','hotaloha','batsofp','papso','osp','hausgarten'};
nLocs = length(locationOrderInModel);

% For plotting purposes
monthLabel = {'Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'};
myColourPalette = brewermap(length(testrunDir),'*Set1');

% =========================================================================
%%
% -------------------------------------------------------------------------
% SECTION 2 - LOAD SELECTED MODEL INPUT AND OUTPUT
% -------------------------------------------------------------------------

for iTest = 1:length(testrunDir)
    currentDir = testrunDir{iTest};
    fullpathTestDir           = fullfile('.','tests',currentDir);
    fullpathModelRunsDir      = fullfile(fullpathTestDir,'modelruns');
    fullpathModelInputDataDir = fullfile(fullpathTestDir,'modelinputdata');
    
    % Output
    load(fullfile(fullpathModelRunsDir,filenameInputSlamsOutput),'output')
    tmpOutput = extractModelOutput(output);

    % Extract flux components
    tracers = struct(...
        'POC', tmpOutput.monthlyOrgCarbonFlux,...% + tmpOutput.monthlyTepFlux, ...
        'PIC', tmpOutput.monthlyCalciteFlux, ...
        'BSi', tmpOutput.monthlyOpalFlux ...
    );
    tracerNames = fieldnames(tracers);

    modFluxMonthlyProfile = NaN([size(tracers.POC), numel(tracerNames)]); % nDepths x 12 months x nLocs x 3 tracers
    for iTracer = 1:numel(tracerNames)
        modFluxMonthlyProfile(:,:,:,iTracer) = tracers.(tracerNames{iTracer}); 
    end 

    % Extract particle numbers
    modPnumMonthlyProfile = squeeze(sum(tmpOutput.monthlyParticleNumInSc,1)); % sum across all size classes

    % Define output array and load configuration parameters
    if iTest == 1
        arrayFluxes = NaN([size(modFluxMonthlyProfile),length(testrunDir)]);
        arrayPnum = NaN([size(modPnumMonthlyProfile),length(testrunDir)]);

        % Input (generated by createSlamsInputData.m)
        load(fullfile(fullpathModelInputDataDir,filenameInputForcing),'mapStruct'); 
  
        config = loadModelConfigurationParameters(fullpathModelInputDataDir,...
            filenameInputRunGrid,filenameInputNumDepthLayers,choiceTypeGridDomain);
    end

    % Store fluxes in output array
    arrayFluxes(:,:,:,:,iTest) = modFluxMonthlyProfile;
    arrayPnum(:,:,:,iTest) = modPnumMonthlyProfile;

end    

% =========================================================================
%%
% -------------------------------------------------------------------------
% SECTION 3 - PLOT MODELLED FLUX DATA BY STATION AND MONTH
% -------------------------------------------------------------------------

for iTracer = 1:3
    for iLoc = 1:nLocs
    
        figure()
        set(gcf,'Units','Normalized','Position',[0.01 0.05 0.25 0.75],'Color','w')
        haxis = zeros(12,1);
        
        for iMonth = 1:12
            haxis(iMonth) = subaxis(4,3,iMonth,'Spacing',0.055,'Padding',0,'Margin',0.13);
            ax(iMonth).pos = get(haxis(iMonth),'Position');

            for iTest = 1:length(testrunDir)
                currMonthModData = arrayFluxes(:,iMonth,iLoc,iTracer,iTest);
                currMonthModDepths = config.availSedTrapDeployDepths;

                d(iTest) = plot(currMonthModData, currMonthModDepths, 'o',...
                    'MarkerEdgeColor', myColourPalette(iTest,:),...
                    'MarkerFaceColor', myColourPalette(iTest,:),...
                    'LineStyle', 'none', 'LineWidth', 0.5,...
                    'MarkerSize', 4, ... 
                    'DisplayName', testLegend{iTest});
                hold on
            end
            hold off

            box on

            if (iTracer == 1)
                xlim([0 320])
                xTickValues = 0:150:300;
            elseif (iTracer == 2)
                xlim([0 520])
                xTickValues = 0:250:500;
            elseif (iTracer == 3)
                xlim([0 150])
                xTickValues = 0:70:140;
            end
            if (iTracer == 1 && (iLoc == 4))
                xlim([0 620])
                xTickValues = 0:300:600;
            elseif (iTracer == 1 && iLoc == 6)
                xlim([0 190])
                xTickValues = 0:70:140;
            elseif (iTracer == 2 && iLoc == 1)
                xlim([0 700])
                xTickValues = 0:300:600;
            elseif (iTracer == 2 && iLoc == 4)
                xlim([0 1050])
                xTickValues = 0:400:800;
            elseif (iTracer == 2 && iLoc == 6)
                xlim([0 350])
                xTickValues = 0:150:300;
            elseif (iTracer == 3 && (iLoc == 2 || iLoc == 3 || iLoc == 6))
                xlim([0 75])
                xTickValues = 0:30:60;
            end

            xticks(xTickValues)
            xticklabels(xTickValues)

            ylim([0 2000])
            yticks([0 500 1000 1500 2000])
            axh = gca;
            axh.YAxis.TickDirection = 'out';
            axh.TickLength = [0.03, 0.03]; % make tick marks longer
    
            if (iMonth == 1 || iMonth == 4 || iMonth ==7 || iMonth == 10)
                yticklabels({'0','500','1000','1500','2000'})
            else
                yticklabels([])
            end
    
            set(gca,'YDir','Reverse','XAxisLocation','Bottom','xlabel',[],'ylabel',[],'FontSize', 11)
    
            title(monthLabel(iMonth),'FontSize',16)
    
        end % iMonth
    
        % Shift all plots a little bit to the right and up
        ax(1).pos(1) = ax(1).pos(1)+0.040; ax(1).pos(2) = ax(1).pos(2)+0.040; 
        ax(2).pos(1) = ax(2).pos(1)+0.025; ax(2).pos(2) = ax(2).pos(2)+0.040; 
        ax(3).pos(1) = ax(3).pos(1)+0.010; ax(3).pos(2) = ax(3).pos(2)+0.040;  
        ax(4).pos(1) = ax(4).pos(1)+0.040; ax(4).pos(2) = ax(4).pos(2)+0.040; 
        ax(5).pos(1) = ax(5).pos(1)+0.025; ax(5).pos(2) = ax(5).pos(2)+0.040; 
        ax(6).pos(1) = ax(6).pos(1)+0.010; ax(6).pos(2) = ax(6).pos(2)+0.040; 
        ax(7).pos(1) = ax(7).pos(1)+0.040; ax(7).pos(2) = ax(7).pos(2)+0.040; 
        ax(8).pos(1) = ax(8).pos(1)+0.025; ax(8).pos(2) = ax(8).pos(2)+0.040; 
        ax(9).pos(1) = ax(9).pos(1)+0.010; ax(9).pos(2) = ax(9).pos(2)+0.040; 
        ax(10).pos(1) = ax(10).pos(1)+0.040; ax(10).pos(2) = ax(10).pos(2)+0.040; 
        ax(11).pos(1) = ax(11).pos(1)+0.025; ax(11).pos(2) = ax(11).pos(2)+0.040; 
        ax(12).pos(1) = ax(12).pos(1)+0.010; ax(12).pos(2) = ax(12).pos(2)+0.040; 
        for iMonth = 1:12
            set(haxis(iMonth),'Position',ax(iMonth).pos) 
        end

        % Some touches to the legend
        lg = legend(d);  % No need to pass legend strings again
        lg.Position(1) = 0.35;
        lg.Position(2) = 0.005;
        lg.Orientation = 'horizontal';
        lg.ItemTokenSize = [20,50];
        lg.FontSize = 11;
        lg.NumColumns = 2;
        lg.Box = 'on';
    
        % Give common xlabel, ylabel and title to your figure
        % Create a new axis
        a = axes;
        t = title(locationOrderInModel(iLoc),'FontSize',18);
        if (iTracer == 1)
            xl = xlabel('POC flux (mg C m^{-2} d^{-1})','FontSize',18);
        elseif (iTracer == 2)
            xl = xlabel('PIC flux (mg calcite m^{-2} d^{-1})','FontSize',18);
        elseif (iTracer == 3)
            xl = xlabel('bSi flux (mg opal m^{-2} d^{-1})','FontSize',18);
        end

        yl = ylabel('Depth (m)','FontSize',18);
        % Specify visibility of the current axis as 'off'
        a.Visible = 'off';
        % Specify visibility of Title, XLabel, and YLabel as 'on'
        t.Visible = 'on';
        xl.Visible = 'on';
        yl.Visible = 'on';
        yl.Position(1) = yl.Position(1) - 0.005; yl.Position(2) = yl.Position(2) + 0.02; 
        xl.Position(1) = 0.5; xl.Position(2) = xl.Position(2) + 0.065;
        t.Position(1) = t.Position(1); t.Position(2) = t.Position(2) + 0.035;
        
        if (iTracer == 1)
            plotTag = 'pocflux';
        elseif (iTracer == 2)
            plotTag = 'picflux';
        elseif (iTracer == 3)
            plotTag = 'bsiflux';
        end
        saveFigureInFolder(figuresSubfolderName,strcat('tests_',plotTag,'_',locationTags{iLoc}))
    
    end % iLoc
end % iTracer

% =========================================================================
%%
% -------------------------------------------------------------------------
% SECTION 4 - PLOT PARTICLE NUMBER DATA BY STATION AND MONTH
% -------------------------------------------------------------------------

for iLoc = 1:nLocs

    figure()
    set(gcf,'Units','Normalized','Position',[0.01 0.05 0.25 0.75],'Color','w')
    haxis = zeros(12,1);
    
    for iMonth = 1:12
        haxis(iMonth) = subaxis(4,3,iMonth,'Spacing',0.055,'Padding',0,'Margin',0.13);
        ax(iMonth).pos = get(haxis(iMonth),'Position');

        for iTest = 1:length(testrunDir)
            currMonthModData = arrayPnum(:,iMonth,iLoc,iTest);
            currMonthModDepths = config.availImagSysDeployDepths;

            % Discard last sampled depth (sea floor)
            idxsSampledDepths = find(currMonthModData ~= 0);
            y = currMonthModDepths(1:numel(idxsSampledDepths)-1)';
            x = currMonthModData(1:numel(idxsSampledDepths)-1,:);

            d(iTest) = plot(x, y, 'o',...
                'MarkerEdgeColor', myColourPalette(iTest,:),...
                'MarkerFaceColor', myColourPalette(iTest,:),...
                'LineStyle', 'none', 'LineWidth', 0.5,...
                'MarkerSize', 4, ... 
                'DisplayName', testLegend{iTest});
            hold on
        end
        hold off

        box on

        set(gca, 'XScale', 'log')
        xlim([1 1e10])                                      
        xticks([1 1000 1e6 1e9])                         
        xticklabels({'1','10^3','10^6','10^9'})   
        set(gca, 'XTickLabelRotation', 0)  % Prevent rotation

        ylim([0 2000])
        yticks([0 500 1000 1500 2000])
        axh = gca;
        axh.YAxis.TickDirection = 'out';
        axh.TickLength = [0.03, 0.03]; % make tick marks longer

        if (iMonth == 1 || iMonth == 4 || iMonth ==7 || iMonth == 10)
            yticklabels({'0','500','1000','1500','2000'})
        else
            yticklabels([])
        end

        set(gca,'YDir','Reverse','XAxisLocation','Bottom','xlabel',[],'ylabel',[],'FontSize', 11)

        title(monthLabel(iMonth),'FontSize',16)

    end % iMonth

    % Shift all plots a little bit to the right and up
    ax(1).pos(1) = ax(1).pos(1)+0.040; ax(1).pos(2) = ax(1).pos(2)+0.040; 
    ax(2).pos(1) = ax(2).pos(1)+0.025; ax(2).pos(2) = ax(2).pos(2)+0.040; 
    ax(3).pos(1) = ax(3).pos(1)+0.010; ax(3).pos(2) = ax(3).pos(2)+0.040;  
    ax(4).pos(1) = ax(4).pos(1)+0.040; ax(4).pos(2) = ax(4).pos(2)+0.040; 
    ax(5).pos(1) = ax(5).pos(1)+0.025; ax(5).pos(2) = ax(5).pos(2)+0.040; 
    ax(6).pos(1) = ax(6).pos(1)+0.010; ax(6).pos(2) = ax(6).pos(2)+0.040; 
    ax(7).pos(1) = ax(7).pos(1)+0.040; ax(7).pos(2) = ax(7).pos(2)+0.040; 
    ax(8).pos(1) = ax(8).pos(1)+0.025; ax(8).pos(2) = ax(8).pos(2)+0.040; 
    ax(9).pos(1) = ax(9).pos(1)+0.010; ax(9).pos(2) = ax(9).pos(2)+0.040; 
    ax(10).pos(1) = ax(10).pos(1)+0.040; ax(10).pos(2) = ax(10).pos(2)+0.040; 
    ax(11).pos(1) = ax(11).pos(1)+0.025; ax(11).pos(2) = ax(11).pos(2)+0.040; 
    ax(12).pos(1) = ax(12).pos(1)+0.010; ax(12).pos(2) = ax(12).pos(2)+0.040; 
    for iMonth = 1:12
        set(haxis(iMonth),'Position',ax(iMonth).pos) 
    end

    % Some touches to the legend
    lg = legend(d);  % No need to pass legend strings again
    lg.Position(1) = 0.35;
    lg.Position(2) = 0.005;
    lg.Orientation = 'horizontal';
    lg.ItemTokenSize = [20,50];
    lg.FontSize = 12;
    lg.NumColumns = 2;
    lg.Box = 'on';

    % Give common xlabel, ylabel and title to your figure
    % Create a new axis
    a = axes;
    t = title(locationOrderInModel(iLoc),'FontSize',18);
    xl = xlabel('Particle number concentration (#/L)','FontSize',18);

    yl = ylabel('Depth (m)','FontSize',18);
    % Specify visibility of the current axis as 'off'
    a.Visible = 'off';
    % Specify visibility of Title, XLabel, and YLabel as 'on'
    t.Visible = 'on';
    xl.Visible = 'on';
    yl.Visible = 'on';
    yl.Position(1) = yl.Position(1) - 0.005; yl.Position(2) = yl.Position(2) + 0.02; 
    xl.Position(1) = 0.5; xl.Position(2) = xl.Position(2) + 0.065;
    t.Position(1) = t.Position(1); t.Position(2) = t.Position(2) + 0.035;

    saveFigureInFolder(figuresSubfolderName,strcat('tests_','pnum','_',locationTags{iLoc}))

end % iLoc

% =========================================================================
%%
% -------------------------------------------------------------------------
% SECTION 5 - ORGANISE ALL INPUT DATA FOR MAPPING
% -------------------------------------------------------------------------

nppInput = mapStruct.monthlyNpp.*3600*24*config.molarMassCarbon*1e3; % mol C m-2 s-1 --> mg C m-2 d-1 

figure;
hold on;
for iLoc = 1:nLocs
    plot((1:12), nppInput(:,iLoc), 'o-', 'LineWidth', 1.5, 'DisplayName', locationOrderInModel{iLoc});
end
hold off;

xlabel('Month');
ylabel('NPP (mg C m^{-2} d^{-1}');
xticks((1:12));
xticklabels(monthLabel);
legend('Location', 'best');
grid on;


