function seqOutput = extractModelOutput(output)

    % Organise it
    monthlyOutput = struct(...
        'OrgCarbonFlux', squeeze(output.flux.monthly(1,:,:,:)),...
        'TepFlux', squeeze(output.flux.monthly(2,:,:,:)),...
        'CalciteFlux', squeeze(output.flux.monthly(3,:,:,:)),...
        'OpalFlux', squeeze(output.flux.monthly(4,:,:,:)),...
        'ParticleNumInSc', squeeze(output.particle.avgAttInScMonthly(:,:,1,:,:)),...
        'ParticleNumInVc', squeeze(output.particle.avgAttInVcMonthly(:,:,1,:,:))...
    );
    
    annualOutput = struct(...
        'OrgCarbonFlux', squeeze(output.flux.annual(1,:,:,:)),...
        'TepFlux', squeeze(output.flux.annual(2,:,:,:)),...
        'CalciteFlux', squeeze(output.flux.annual(3,:,:,:)),...
        'OpalFlux', squeeze(output.flux.annual(4,:,:,:)),...
        'ParticleNumInSc', squeeze(output.particle.avgAttInScAnnual(:,:,1,:)),...
        'ParticleAvgAttByMainSc', output.particle.avgAttScAtDepthAnnual,...
        'ParticleAvgAttByPartType', output.particle.avgAttInTyAnnual,...
        'SMS', output.sms.annual,...
        'Aux', output.aux.annual...
    );

    seasonalOutput = struct(...
        'ParticleAvgAttByMainSc', output.seasonal.particle.avgAttScAtDepth,...
        'ParticleAvgAttByMainVc', output.seasonal.particle.avgAttVcAtDepth...
    );

    % Combine monthly, annual and seasonal data
    outputStructs = {monthlyOutput, annualOutput, seasonalOutput};
    periodTypes = ["monthly", "annual", "seasonal"];

    seqOutput = struct();
    for iPeriod = 1:numel(periodTypes)
        dataStruct = outputStructs{iPeriod};
        periodType = periodTypes(iPeriod);

        % Iterate through fields and store in seqOutput
        fieldNames = fieldnames(dataStruct);
        for iField = 1:numel(fieldNames)
            fieldName = fieldNames{iField};
            seqOutput.(periodType + fieldName) = dataStruct.(fieldName);
        end
    end
    
end % extractModelOutput